language: julia

os:
  - osx
  - linux

julia:
  - 1.3
  
notifications:
  email: false
 
before_install:
   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia -p 4 --check-bounds=yes -e 'using Pkg; Pkg.build(); Pkg.test("jInvSeismic";coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("jInvSeismic")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'